import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { email, deviceName, serialNumber, status, pdfBase64, passportUrl } = await req.json();

    const RESEND_API_KEY = process.env.RESEND_API_KEY;

    if (!RESEND_API_KEY) {
      return NextResponse.json({ error: 'Resend API Key is not configured' }, { status: 500 });
    }

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: 'Dulang Device Passport <onboarding@resend.dev>',
        to: email,
        subject: `Asset Report: ${deviceName}`,
        html: `
          <div style="font-family: sans-serif; padding: 20px; color: #333;">
            <h1 style="color: #2e7d32;">Asset Security Report</h1>
            <p>You are receiving a digital passport report for the following asset:</p>
            <div style="background: #f8f9fa; padding: 20px; border-radius: 10px; margin: 20px 0;">
              <p><strong>Device:</strong> ${deviceName}</p>
              <p><strong>Serial Number:</strong> ${serialNumber}</p>
              <p><strong>Status:</strong> ${status}</p>
            </div>
            <p>You can view the live digital passport here:</p>
            <a href="${passportUrl}" style="background: #2e7d32; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; display: inline-block;">View Live Passport</a>
            <p style="margin-top: 30px; font-size: 12px; color: #999;">Generated by Dulang Device Passport System.</p>
          </div>
        `,
        attachments: pdfBase64 ? [
          {
            filename: `${deviceName.replace(/\s+/g, '_')}_Report.pdf`,
            content: pdfBase64.split(',')[1],
          },
        ] : [],
      }),
    });

    const data = await res.json();
    return NextResponse.json(data);
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 });
  }
}
