import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { email, deviceName, serialNumber, status, pdfBase64, passportUrl } = await req.json();

    const RESEND_API_KEY = process.env.RESEND_API_KEY;

    if (!RESEND_API_KEY) {
      console.error("Email Error: RESEND_API_KEY is missing from environment variables.");
      return NextResponse.json({ error: 'System Configuration Error (API Key Missing)' }, { status: 500 });
    }

    console.log(`Attempting to send email to ${email} for device ${deviceName}`);

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: 'Dulang Asset Registry <onboarding@resend.dev>',
        to: email,
        subject: `[Dulang] Asset Report: ${deviceName}`,
        html: `
          <div style="font-family: sans-serif; padding: 30px; color: #1a1a1a; max-width: 600px; margin: auto; border: 1px solid #eee; border-radius: 20px;">
            <div style="text-align: center; margin-bottom: 30px;">
              <h1 style="color: #2e7d32; margin: 0; font-size: 24px;">Asset Identity Passport</h1>
              <p style="color: #666; font-size: 14px; margin-top: 5px;">Enterprise Digital Registry Report</p>
            </div>
            
            <div style="background: #f8f9fa; padding: 25px; border-radius: 15px; margin: 20px 0; border: 1px solid #f0f0f0;">
              <p style="margin: 0 0 10px 0; font-size: 12px; font-weight: bold; color: #999; text-transform: uppercase; letter-spacing: 1px;">Device Identity</p>
              <h2 style="margin: 0; color: #000; font-size: 20px;">${deviceName}</h2>
              <div style="margin-top: 15px; display: grid; gap: 10px;">
                <p style="margin: 0; font-size: 14px;"><strong>Serial Number:</strong> <span style="font-family: monospace;">${serialNumber}</span></p>
                <p style="margin: 0; font-size: 14px;"><strong>System Status:</strong> <span style="color: ${status === 'Healthy' ? '#2e7d32' : '#d32f2f'}; font-weight: bold;">${status}</span></p>
              </div>
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
              <p style="font-size: 14px; color: #666; margin-bottom: 20px;">You can access the live digital passport and full maintenance history via the secure link below:</p>
              <a href="${passportUrl}" style="background: #2e7d32; color: white; padding: 16px 32px; border-radius: 12px; text-decoration: none; display: inline-block; font-weight: bold; font-size: 14px; box-shadow: 0 4px 12px rgba(46,125,50,0.2);">ACCESS DIGITAL PASSPORT</a>
            </div>
            
            <hr style="border: 0; border-top: 1px solid #eee; margin: 30px 0;" />
            
            <p style="font-size: 11px; color: #999; line-height: 1.6; text-align: center;">
              This report was generated by the Dulang Asset Management System. 
              If you are using a Resend free tier account, please ensure the recipient email is verified in your Resend dashboard.
            </p>
          </div>
        `,
        attachments: pdfBase64 ? [
          {
            filename: `${deviceName.replace(/\s+/g, '_')}_Identity_Passport.pdf`,
            content: pdfBase64.split(',')[1],
          },
        ] : [],
      }),
    });

    const data = await res.json();
    
    if (!res.ok) {
      console.error("Resend API Error:", data);
      return NextResponse.json({ error: data.message || 'Resend API rejected the request' }, { status: res.status });
    }

    return NextResponse.json(data);
  } catch (error: any) {
    console.error("Fatal Email Error:", error);
    return NextResponse.json({ error: error.message || 'Failed to connect to email service' }, { status: 500 });
  }
}
